version: '3'
services:
  keycloak:
    container_name: "${SHANOIR_PREFIX}keycloak"
    environment:
      - SHANOIR_ADMIN_EMAIL
      - SHANOIR_ADMIN_NAME
      - SHANOIR_URL_HOST
      - SHANOIR_URL_SCHEME
      - SHANOIR_SMTP_HOST
      - SHANOIR_MIGRATION
      - SHANOIR_KEYCLOAK_USER
      - SHANOIR_KEYCLOAK_PASSWORD
      - SHANOIR_ALLOWED_ADMIN_IPS
      - SHANOIR_DB_ADDR
      - SHANOIR_KEYCLOAK_DB_PORT
    restart: always
    build: ./docker-compose/keycloak
    networks:
      - shanoir_ng_network
    ports:
      - "8180:8443"

  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=inr_wordpress
      - MARIADB_DATABASE=inr_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'docker.io/bitnami/wordpress-nginx:5-debian-10'
    ports:
      - '8012:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - './wordpress/wordpress-server-block.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf:ro'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=inr_wordpress
      - WORDPRESS_DATABASE_NAME=inr_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    
  nginx:
    container_name: shanoir-ng-nginx
    build: ./docker-compose/nginx
    environment:
      - SHANOIR_PREFIX
      - SHANOIR_URL_HOST
      - SHANOIR_URL_SCHEME
      - SHANOIR_X_FORWARDED
      - SHANOIR_COLORS
    volumes:
      - "logs:/var/log/nginx"
      - certificate-share-data:/opt/ssl:ro
    networks: 
      - shanoir_ng_network
    ports:
     - "443:443"
    depends_on:
      - "keycloak"

volumes:
  certificate-share-data:
  logs:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  shanoir_ng_network:
